ALTER TABLE BEAN.BRD_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.BRD_DATA CASCADE CONSTRAINTS;

CREATE TABLE BEAN.BRD_DATA
(
  IDX       NUMBER,
  BRD_IDX   NUMBER,
  BRD_ID    VARCHAR2(20 BYTE),
  TITLE     VARCHAR2(100 BYTE)                  NOT NULL,
  SUBJECT   VARCHAR2(30 BYTE),
  CONTENTS  VARCHAR2(4000 BYTE),
  HIT_CNT   NUMBER                              NOT NULL,
  DEL_YN    VARCHAR2(1 BYTE)                    DEFAULT 'N'                   NOT NULL,
  REG_DATE  DATE                                DEFAULT SYSDATE               NOT NULL,
  MOD_DATE  DATE                                DEFAULT SYSDATE               NOT NULL,
  REG_ID    VARCHAR2(30 BYTE)                   NOT NULL,
  MOD_ID    VARCHAR2(30 BYTE)                   NOT NULL,
  PRIMARY KEY
  (IDX)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BEAN.BRD_DATA IS '공지사항 게시판';

COMMENT ON COLUMN BEAN.BRD_DATA.IDX IS '인덱스';

COMMENT ON COLUMN BEAN.BRD_DATA.BRD_IDX IS '부모글 인덱스';

COMMENT ON COLUMN BEAN.BRD_DATA.BRD_ID IS '게시판구분';

COMMENT ON COLUMN BEAN.BRD_DATA.TITLE IS '제목';

COMMENT ON COLUMN BEAN.BRD_DATA.SUBJECT IS '말머리';

COMMENT ON COLUMN BEAN.BRD_DATA.CONTENTS IS '내용';

COMMENT ON COLUMN BEAN.BRD_DATA.HIT_CNT IS '조회수';

COMMENT ON COLUMN BEAN.BRD_DATA.DEL_YN IS '삭제구분';

COMMENT ON COLUMN BEAN.BRD_DATA.REG_DATE IS '등록일자';

COMMENT ON COLUMN BEAN.BRD_DATA.MOD_DATE IS '등록일자';

COMMENT ON COLUMN BEAN.BRD_DATA.REG_ID IS '등록자 ID';

COMMENT ON COLUMN BEAN.BRD_DATA.MOD_ID IS '등록일자';



ALTER TABLE BEAN.BRD_FILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.BRD_FILE CASCADE CONSTRAINTS;

CREATE TABLE BEAN.BRD_FILE
(
  FILEIDX             NUMBER,
  BRD_ID              VARCHAR2(20 BYTE)         NOT NULL,
  ORIGINAL_FILE_NAME  VARCHAR2(260 BYTE)        NOT NULL,
  STORED_FILE_NAME    VARCHAR2(36 BYTE)         NOT NULL,
  FILE_SIZE           NUMBER,
  REG_DATE            DATE                      DEFAULT SYSDATE               NOT NULL,
  REG_ID              VARCHAR2(30 BYTE)         NOT NULL,
  DEL_YN              VARCHAR2(1 BYTE)          DEFAULT 'N'                   NOT NULL,
  BRD_IDX             NUMBER,
  FILE_EXT            VARCHAR2(20 BYTE),
  PRIMARY KEY
  (FILEIDX)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.BRD_FILE.FILEIDX IS '순서';

COMMENT ON COLUMN BEAN.BRD_FILE.BRD_ID IS '게시판종류';

COMMENT ON COLUMN BEAN.BRD_FILE.ORIGINAL_FILE_NAME IS '파일이름';

COMMENT ON COLUMN BEAN.BRD_FILE.STORED_FILE_NAME IS '파일이름(변경)';

COMMENT ON COLUMN BEAN.BRD_FILE.FILE_SIZE IS '크기';

COMMENT ON COLUMN BEAN.BRD_FILE.REG_DATE IS '등록일';

COMMENT ON COLUMN BEAN.BRD_FILE.REG_ID IS '아이디';

COMMENT ON COLUMN BEAN.BRD_FILE.DEL_YN IS '삭제구분';

COMMENT ON COLUMN BEAN.BRD_FILE.BRD_IDX IS '종류별순서';

COMMENT ON COLUMN BEAN.BRD_FILE.FILE_EXT IS '파일확장자';



ALTER TABLE BEAN.COMMON_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.COMMON_CODE CASCADE CONSTRAINTS;

CREATE TABLE BEAN.COMMON_CODE
(
  CODE       NUMBER                             NOT NULL,
  CODE_NAME  VARCHAR2(20 BYTE)                  NOT NULL,
  USE_YN     VARCHAR2(2 BYTE)                   NOT NULL,
  REG_ID     VARCHAR2(20 BYTE),
  REG_DATE   DATE,
  MOD_ID     VARCHAR2(20 BYTE),
  MOD_DATE   DATE,
  NO         NUMBER                             NOT NULL,
  CONSTRAINT COMMON_CODE_PK
  PRIMARY KEY
  (CODE, CODE_NAME, NO)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.COMMON_CODE.CODE IS '코드값';

COMMENT ON COLUMN BEAN.COMMON_CODE.CODE_NAME IS '코드이름';

COMMENT ON COLUMN BEAN.COMMON_CODE.USE_YN IS '사용구분';

COMMENT ON COLUMN BEAN.COMMON_CODE.REG_ID IS '등록자';

COMMENT ON COLUMN BEAN.COMMON_CODE.REG_DATE IS '등록일자';

COMMENT ON COLUMN BEAN.COMMON_CODE.MOD_ID IS '수정자';

COMMENT ON COLUMN BEAN.COMMON_CODE.MOD_DATE IS '수정일자';

COMMENT ON COLUMN BEAN.COMMON_CODE.NO IS '번호';



ALTER TABLE BEAN.COMMON_CODE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.COMMON_CODE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BEAN.COMMON_CODE_DETAIL
(
  CODE        NUMBER                            NOT NULL,
  CODE_NAME   VARCHAR2(20 BYTE)                 NOT NULL,
  VAR_CODE    VARCHAR2(20 BYTE)                 NOT NULL,
  VAR_NAME    VARCHAR2(20 BYTE)                 NOT NULL,
  REF_1       VARCHAR2(20 BYTE),
  REF_2       VARCHAR2(20 BYTE),
  REF_3       VARCHAR2(20 BYTE),
  REG_ID      VARCHAR2(20 BYTE),
  REG_DATE    DATE,
  MOD_ID      VARCHAR2(20 BYTE),
  MOD_DATE    DATE,
  CODE_ORDER  NUMBER,
  DETAIL_NO   NUMBER                            NOT NULL,
  CONSTRAINT COMMON_CODE_DETAIL_PK
  PRIMARY KEY
  (CODE, CODE_NAME, DETAIL_NO)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.CODE IS '코드값';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.CODE_NAME IS '코드이름';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.VAR_CODE IS '변수이름';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.VAR_NAME IS '변수값';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.REF_1 IS '참조1';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.REF_2 IS '참조2';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.REF_3 IS '참조3';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.REG_ID IS '등록자';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.REG_DATE IS '등록일자';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.MOD_ID IS '수정자';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.MOD_DATE IS '수정일자';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.CODE_ORDER IS '순번';

COMMENT ON COLUMN BEAN.COMMON_CODE_DETAIL.DETAIL_NO IS '번호';



ALTER TABLE BEAN.MEMBER_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.MEMBER_INFO CASCADE CONSTRAINTS;

CREATE TABLE BEAN.MEMBER_INFO
(
  MEMBER_NO    NUMBER                           NOT NULL,
  MEMBER_ID    VARCHAR2(150 BYTE)               NOT NULL,
  MEMBER_PWD   VARCHAR2(150 BYTE),
  MEMBER_ROLE  VARCHAR2(20 BYTE),
  MEMBER_NICK  VARCHAR2(20 BYTE),
  MEMBER_NAME  VARCHAR2(30 BYTE),
  DEL_YN       VARCHAR2(2 BYTE),
  MEMBER_TYPE  VARCHAR2(20 BYTE),
  CONSTRAINT MEMBER_INFO_PK
  PRIMARY KEY
  (MEMBER_ID, MEMBER_NO)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_NO IS '번호';

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_ID IS '아이디';

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_PWD IS '비밀번호';

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_ROLE IS '유저권한';

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_NICK IS '별명';

COMMENT ON COLUMN BEAN.MEMBER_INFO.MEMBER_NAME IS '유저이름';

COMMENT ON COLUMN BEAN.MEMBER_INFO.DEL_YN IS '삭제구분';



ALTER TABLE BEAN.MEMBER_INFO_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.MEMBER_INFO_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BEAN.MEMBER_INFO_DETAIL
(
  MEMBER_ID        VARCHAR2(150 BYTE)           NOT NULL,
  MEMBER_TEL       VARCHAR2(20 BYTE),
  MEMBER_PHONE     VARCHAR2(20 BYTE),
  MEMBER_EMAIL     VARCHAR2(50 BYTE),
  MEMBER_ADDR      VARCHAR2(20 BYTE),
  MEMBER_ADDR_2    VARCHAR2(20 BYTE),
  MEMBER_ENG_NAME  VARCHAR2(20 BYTE),
  CRE_DATE         DATE                         DEFAULT SYSDATE,
  MOD_DATE         DATE                         DEFAULT SYSDATE,
  USE_YN           VARCHAR2(2 BYTE),
  MEMBER_NO        NUMBER,
  CONSTRAINT MEMBER_INFO_DETAIL_PK
  PRIMARY KEY
  (MEMBER_NO, MEMBER_ID)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_ID IS '아이디';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_TEL IS '전화번호';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_PHONE IS '핸드폰';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_EMAIL IS '이메일';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_ADDR IS '집주소';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_ADDR_2 IS '집주소2';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MEMBER_ENG_NAME IS '영어이름';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.CRE_DATE IS '생성일';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.MOD_DATE IS '수정일';

COMMENT ON COLUMN BEAN.MEMBER_INFO_DETAIL.USE_YN IS '사용구분';



ALTER TABLE BEAN.ROLE_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.ROLE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE BEAN.ROLE_GROUP
(
  NO            INTEGER,
  ROLE_CHAR     VARCHAR2(20 BYTE)               NOT NULL,
  MENU_NO       INTEGER                         NOT NULL,
  MENU_ID       VARCHAR2(30 BYTE)               NOT NULL,
  MENU_NAME     VARCHAR2(30 BYTE)               NOT NULL,
  READ_GRANT    VARCHAR2(1 BYTE)                NOT NULL,
  WRITE_GRANT   VARCHAR2(1 BYTE)                NOT NULL,
  DELETE_GRANT  VARCHAR2(1 BYTE)                NOT NULL,
  ETC           VARCHAR2(20 BYTE),
  REG_ID        VARCHAR2(20 BYTE)               NOT NULL,
  REG_DATE      DATE                            NOT NULL,
  PRIMARY KEY
  (NO)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BEAN.ROLE_MENU
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.ROLE_MENU CASCADE CONSTRAINTS;

CREATE TABLE BEAN.ROLE_MENU
(
  NO         NUMBER                             NOT NULL,
  DEPTH_1    NUMBER,
  DEPTH_2    NUMBER,
  DEPTH_3    NUMBER,
  ETC1       VARCHAR2(20 BYTE),
  ETC2       VARCHAR2(20 BYTE),
  MENU_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  MENU_NAME  VARCHAR2(20 BYTE)                  NOT NULL,
  MENU_URL   VARCHAR2(100 BYTE),
  SORT       NUMBER,
  USE_YN     VARCHAR2(2 BYTE),
  ADMIN_YN   VARCHAR2(2 BYTE),
  REG_ID     VARCHAR2(30 BYTE),
  REG_DATE   DATE,
  MOD_ID     VARCHAR2(30 BYTE),
  MOD_DATE   DATE,
  CONSTRAINT ROLE_MENU_PK2
  PRIMARY KEY
  (NO, MENU_ID)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BEAN.ROLE_MENU.NO IS '번호';

COMMENT ON COLUMN BEAN.ROLE_MENU.DEPTH_1 IS '부모메뉴';

COMMENT ON COLUMN BEAN.ROLE_MENU.DEPTH_2 IS '자식메뉴';

COMMENT ON COLUMN BEAN.ROLE_MENU.DEPTH_3 IS '참조메뉴';

COMMENT ON COLUMN BEAN.ROLE_MENU.ETC1 IS '참조1';

COMMENT ON COLUMN BEAN.ROLE_MENU.ETC2 IS '참조2';

COMMENT ON COLUMN BEAN.ROLE_MENU.MENU_ID IS '메뉴ID';

COMMENT ON COLUMN BEAN.ROLE_MENU.MENU_NAME IS '메뉴이름';

COMMENT ON COLUMN BEAN.ROLE_MENU.MENU_URL IS '메뉴URL';

COMMENT ON COLUMN BEAN.ROLE_MENU.SORT IS '정렬';

COMMENT ON COLUMN BEAN.ROLE_MENU.USE_YN IS '사용구분';

COMMENT ON COLUMN BEAN.ROLE_MENU.ADMIN_YN IS '관리자구분';

COMMENT ON COLUMN BEAN.ROLE_MENU.REG_ID IS '등록한ID';

COMMENT ON COLUMN BEAN.ROLE_MENU.REG_DATE IS '등록일';

COMMENT ON COLUMN BEAN.ROLE_MENU.MOD_ID IS '수정한ID';

COMMENT ON COLUMN BEAN.ROLE_MENU.MOD_DATE IS '수정일';



ALTER TABLE BEAN.TB_SEQ
 DROP PRIMARY KEY CASCADE;

DROP TABLE BEAN.TB_SEQ CASCADE CONSTRAINTS;

CREATE TABLE BEAN.TB_SEQ
(
  NO        NUMBER,
  SEQ_NO    NUMBER,
  SEQ_CODE  VARCHAR2(30 BYTE),
  SEQ_NAME  VARCHAR2(30 BYTE),
  ETC       VARCHAR2(30 BYTE),
  REG_DATE  DATE,
  CONSTRAINT TB_SEQ_PK
  PRIMARY KEY
  (NO)
  USING INDEX
    TABLESPACE TS_BEAN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE
)
TABLESPACE TS_BEAN
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;










CREATE UNIQUE INDEX BEAN.ROLE_MENU_PK ON BEAN.ROLE_MENU
(NO)
LOGGING
TABLESPACE TS_BEAN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;




--  There is no statement for index BEAN.SYS_C0014114.
--  The object is created when the parent object is created.

--  There is no statement for index BEAN.SYS_C0014763.
--  The object is created when the parent object is created.

--  There is no statement for index BEAN.SYS_C0014792.
--  The object is created when the parent object is created.
