
CREATE TABLE BRD_DATA
(
   IDX INT NOT NULL COMMENT '인덱스',
   BRD_IDX INT COMMENT '게시판 인덱스',
   BRD_ID VARCHAR(100) NOT NULL COMMENT '게시판아이디',
   TITLE VARCHAR(100) NOT NULL COMMENT '제목',
   SUBJECT VARCHAR(30) COMMENT '말머리',
   CONTENTS VARCHAR(4000) COMMENT '내용',
   HIT_CNT INT NOT NULL COMMENT '조회수',
   DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제구분',
   REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT  '등록일자',
   MOD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT  '수정일자',
   REG_ID VARCHAR(30) NOT NULL COMMENT '등록자 아이디',
   MOD_ID VARCHAR(30) NOT NULL COMMENT '수정자 아이디',
  PRIMARY KEY (IDX)
) ENGINE = InnoDB COMMENT = '공통게시판' ROW_FORMAT = DEFAULT;


CREATE TABLE BRD_FILE
(
  FILEIDX INT NOT NULL COMMENT '인덱스',           
  BRD_ID VARCHAR(20) NOT NULL COMMENT '게시판종류',            
  ORIGINAL_FILE_NAME VARCHAR(260) NOT NULL COMMENT '파일이름',
  STORED_FILE_NAME VARCHAR(36)  NOT NULL COMMENT '파일이름(변경)',
  FILE_SIZE INT COMMENT '크기',
  REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  REG_ID VARCHAR(30) NOT NULL COMMENT '아이디',
  DEL_YN VARCHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제구분',   
  BRD_IDX INT COMMENT '종류별순서',
  FILE_EXT VARCHAR(20) COMMENT '파일확장자',
  PRIMARY KEY (FILEIDX)
) ENGINE = InnoDB COMMENT = '파일첨부게시판' ROW_FORMAT = DEFAULT;


CREATE TABLE COMMON_CODE
(
  CODE       INT     NOT NULL COMMENT '코드값',
  CODE_NAME  VARCHAR(20)  NOT NULL COMMENT '코드이름',
  USE_YN     VARCHAR(2)   NOT NULL COMMENT '사용구분',
  REG_ID     VARCHAR(20) COMMENT '등록자 아이디',
  REG_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  MOD_ID     VARCHAR(20) COMMENT '수정자 아이디',
  MOD_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  NO 		 INT     NOT NULL COMMENT '번호',
  PRIMARY KEY(CODE, CODE_NAME, NO)
 ) ENGINE = InnoDB COMMENT = '공통코드' ROW_FORMAT = DEFAULT;


CREATE TABLE COMMON_CODE_DETAIL
(
  DETAIL_NO   INT    NOT NULL COMMENT '번호',
  CODE INT    NOT NULL COMMENT '코드값',
  CODE_NAME   VARCHAR(20) NOT NULL COMMENT '코드이름',
  VAR_CODE    VARCHAR(20) NOT NULL COMMENT '변수이름',
  VAR_NAME    VARCHAR(20) NOT NULL COMMENT '변수값',
  REF_1       VARCHAR(20) COMMENT '참조1',
  REF_2       VARCHAR(20) COMMENT '참조2',
  REF_3       VARCHAR(20) COMMENT '참조3',
  REG_ID      VARCHAR(20) COMMENT '등록자',
  REG_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  MOD_ID      VARCHAR(20) COMMENT '수정자',
  MOD_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  CODE_ORDER  INT COMMENT '순번',
  PRIMARY KEY(CODE, CODE_NAME, DETAIL_NO)
) ENGINE = InnoDB COMMENT = '공통코드상세정보' ROW_FORMAT = DEFAULT;



CREATE TABLE MEMBER_INFO
(
  MEMBER_NO    INT   NOT NULL COMMENT '번호',
  MEMBER_ID    VARCHAR(150)       NOT NULL COMMENT '아이디',
  MEMBER_PWD   VARCHAR(150) COMMENT '비밀번호',
  MEMBER_ROLE  VARCHAR(20) COMMENT '유저권한',
  MEMBER_NICK  VARCHAR(20) COMMENT '별명',
  MEMBER_NAME  VARCHAR(30) COMMENT '유저이름',
  MEMBER_TYPE  VARCHAR(20) COMMENT '회원가입유형',
  DEL_YN       VARCHAR(2) DEFAULT 'N' COMMENT '삭제구분',
  PRIMARY KEY(MEMBER_ID, MEMBER_NO)
) ENGINE = InnoDB COMMENT = '회원정보' ROW_FORMAT = DEFAULT;



CREATE TABLE MEMBER_INFO_DETAIL
(
  MEMBER_NO INT COMMENT '번호',
  MEMBER_ID VARCHAR(150)   NOT NULL COMMENT '아이디',
  MEMBER_TEL       VARCHAR(20) COMMENT '전화번호',
  MEMBER_PHONE     VARCHAR(20) COMMENT '핸드폰',
  MEMBER_EMAIL     VARCHAR(50) COMMENT '이메일',
  MEMBER_ADDR      VARCHAR(20) COMMENT '집주소',
  MEMBER_ADDR_2    VARCHAR(20) COMMENT '집주소2',
  MEMBER_ENG_NAME  VARCHAR(20) COMMENT '영어이름',
  CRE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  MOD_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  USE_YN   VARCHAR(2) COMMENT '사용구분',
  PRIMARY KEY
  (MEMBER_NO, MEMBER_ID)
) ENGINE = InnoDB COMMENT = '회원상세정보' ROW_FORMAT = DEFAULT;


CREATE TABLE ROLE_GROUP
(
  NO    INT NOT NULL COMMENT '번호',
  ROLE_CHAR     VARCHAR(20) NOT NULL COMMENT '권한이름',
  MENU_NO       INT NOT NULL COMMENT '메뉴번호',
  MENU_ID       VARCHAR(30)       NOT NULL COMMENT '메뉴 아이디',
  MENU_NAME     VARCHAR(30)       NOT NULL COMMENT '메뉴이름',
  READ_GRANT    VARCHAR(1)NOT NULL COMMENT '읽기권한',
  WRITE_GRANT   VARCHAR(1)NOT NULL COMMENT '쓰기권한',
  DELETE_GRANT  VARCHAR(1)NOT NULL COMMENT '삭제권한',
  ETC   VARCHAR(20) COMMENT '기타',
  REG_ID VARCHAR(20)       NOT NULL COMMENT '등록자 아이디',
  REG_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
  PRIMARY KEY (NO)
) ENGINE = InnoDB COMMENT = '권한그룹' ROW_FORMAT = DEFAULT;



CREATE TABLE ROLE_MENU
(
  NO INT     NOT NULL COMMENT '번호',
  DEPTH_1    INT COMMENT '대메뉴',
  DEPTH_2    INT COMMENT '중메뉴',
  DEPTH_3    INT COMMENT '소메뉴',
  ETC1       VARCHAR(20) COMMENT '기타',
  ETC2       VARCHAR(20) COMMENT '기타',
  MENU_ID    VARCHAR(20)  NOT NULL COMMENT '메뉴 아이디',
  MENU_NAME  VARCHAR(20)  NOT NULL COMMENT '메뉴이름',
  MENU_URL   VARCHAR(100) COMMENT '메뉴URL',
  SORT       INT COMMENT '순서',
  USE_YN     VARCHAR(2) COMMENT '사용구분',
  ADMIN_YN   VARCHAR(2) COMMENT '관리자메뉴구분',
  REG_ID     VARCHAR(30) COMMENT '등록자 아이디',
  REG_DATE   TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
  MOD_ID     VARCHAR(30) COMMENT '수정자 아이디',
  MOD_DATE   TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '수정일자',
  PRIMARY KEY
  (NO, MENU_ID)
) ENGINE = InnoDB COMMENT = '메뉴' ROW_FORMAT = DEFAULT;


CREATE TABLE TB_SEQ
(
  NO INT NOT NULL COMMENT '번호',
  SEQ_NO    INT COMMENT '시퀀스번호',
  SEQ_CODE  VARCHAR(30) COMMENT '시퀀스코드',
  SEQ_NAME  VARCHAR(30) COMMENT '시퀀스이름',
  ETC       VARCHAR(30) COMMENT '기타',
  REG_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록일자',
  PRIMARY KEY
  (NO)
) ENGINE = InnoDB COMMENT = '시퀀스 게시판' ROW_FORMAT = DEFAULT;

